#FILENAME:      Makefile
#DESCRIPTION:   convert MEDM screens to other GUI formats


TOP = ../..
include $(TOP)/configure/CONFIG

include $(TOP)/configure/RULES

## add additional directories once the Makefiles have been created
#SUBDIRS = ui
## SUBDIRS += edl


#.PHONY: all subdirs $(SUBDIRS)

#all :: subdirs

#subdirs: $(SUBDIRS)

#$(SUBDIRS):
#	$(MAKE) -C $@
